/*
 * This file was generated by the Gradle 'init' task.
 */

project.ext.properties["kotlin_version"] = PackageVersions.Kotlin

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    kotlin("jvm")
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlin:kotlin-stdlib")

    // Logging
    implementation("org.slf4j:slf4j-api:${PackageVersions.Slf4j}")
    implementation("ch.qos.logback:logback-classic:${PackageVersions.Logback}")
    implementation("ch.qos.logback:logback-core:${PackageVersions.Logback}")
    implementation("io.github.microutils:kotlin-logging:${PackageVersions.MicroUtils}")
    implementation("io.github.microutils:kotlin-logging-jvm:${PackageVersions.MicroUtils}")

    // Jackson
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${PackageVersions.Jackson}")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
