import org.gradle.kotlin.dsl.dependencies

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("com.brashidnia.kotlin-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

dependencies {
//    testImplementation("org.slf4j:slf4j-api:${PackageVersions.Slf4j}")
}