object PackageVersions {
    const val AwsDynamoDb = "1.12.367"
    const val AwsSdk = "2.19.3"
    const val AwsServerless = "1.8.2"
    const val Arrow = "1.2.0-RC"
    const val Caffeine = "3.1.6"
    const val Coroutines = "1.6.4"
    const val Exposed = "0.41.1"
    const val GoogleCloud = "2.25.0"
    const val Jackson = "2.15.+"
    const val HubspotJackson = "0.9.13"
    const val Kotlin = "1.8.22"
    const val Kotlinx = "1.5.1"
    const val Ktor = "2.0.1"
    const val Logback = "1.4.7"
    const val MicroUtils = "3.0.5"
    const val Moshi = "1.14.0"
    const val Okhttp = "4.10.0"
    const val PbProto = "1.16.0"
    const val Protobuf = "3.23.3"
    const val PbGrpcClient = "2.1.0"
    const val FigureHdWallet = "0.2.3"
    const val PbEventStream = "0.9.0"
    const val SpringDependency = "1.1.0"
    const val SpringBoot = "3.1.0"
    const val Spring = "6.0.3"
    const val Slf4j = "2.0.7"
    const val TestNG = "7.7.1"
}

object PluginVersions {
    const val Protobuf = "0.9.3"
}
